// `refresh-fixtures` — an example writeback run: regenerate files in a
// credential-free container, then let the WORKER propose the diff as a PR.
//
// This is the minimal demonstration of the `writeback` capability
// (specs/02-runs.md § Writeback). The container runs an operator-supplied
// command that regenerates some tracked files (a recorded-API-fixture refresh,
// a `<tool> --write` codegen pass, a snapshot update — anything deterministic),
// then emits a writeback manifest + the changed file blobs to its artifact
// output. It NEVER pushes a branch or opens a PR — it holds no git/gh
// credential. After the run succeeds, the Dispatcher Worker reads the manifest,
// validates it against the `writeback` spec below, and commits it via the
// GitHub App, opening (or updating) a draft PR.
//
// The container contract is conventional, not magic:
//
//   * write `artifacts/writeback/manifest.json` =
//       { "entries": [ { "path": "<repo-relative>", "mode"?, "deleted"? }, … ] }
//   * write each non-deleted entry's content at
//       `artifacts/writeback/files/<repo-relative path>`
//   * `artifact.upload({ name: "writeback", path: "artifacts/writeback",
//      container })` — the directory artifact lands in R2 where the Worker reads
//      it back.
//
// An empty / absent manifest ⇒ a clean no-op (the command produced no diff).
//
// Spec: specs/02-runs.md § Writeback, specs/03-dsl.md § defineRun.

import { Effect, Schema } from "effect";
import {
  artifact,
  defineRun,
  sandbox,
  step,
  WRITEBACK_ARTIFACT,
} from "@fractalboxdev/flare-dispatch-core";
import { workspace } from "@fractalboxdev/flare-dispatch-core/primitives";

const Input = Schema.Struct({
  repo: Schema.String, // "owner/name"
  sha: Schema.String,
  /** The command that regenerates the tracked files (e.g. a codegen / record). */
  command: Schema.String,
});

const Output = Schema.Struct({
  exitCode: Schema.Number,
  /** Repo-relative paths the run staged for writeback (empty ⇒ no diff). */
  changedPaths: Schema.Array(Schema.String),
  /** The writeback artifact URL (the manifest the Worker consumed). */
  writebackUri: Schema.String,
});

/**
 * Stage the writeback payload from `git`'s own view of the working tree:
 *
 *   1. write a manifest listing every tracked-file change (`git status`);
 *   2. copy each changed file's content under `artifacts/writeback/files/…`.
 *
 * Plain POSIX `sh` so no extra CLI is baked into the image. `git status
 * --porcelain` is the source of truth for "what changed" — additions,
 * modifications, and deletions all flow from it.
 */
const STAGE_WRITEBACK_SCRIPT = `
set -eu
out=artifacts/writeback
rm -rf "$out"; mkdir -p "$out/files"
: > "$out/.entries"
git status --porcelain | while IFS= read -r line; do
  status=$(printf '%s' "$line" | cut -c1-2)
  path=$(printf '%s' "$line" | cut -c4-)
  case "$status" in
    *D*) printf '{"path":"%s","deleted":true}\\n' "$path" >> "$out/.entries" ;;
    *)   mkdir -p "$out/files/$(dirname "$path")"
         cp "$path" "$out/files/$path"
         if [ -x "$path" ]; then mode=100755; else mode=100644; fi
         printf '{"path":"%s","mode":"%s"}\\n' "$path" "$mode" >> "$out/.entries" ;;
  esac
done
# Fold the per-line entries into the manifest's entries array.
printf '{"entries":[%s]}\\n' "$(paste -sd, "$out/.entries")" > "$out/manifest.json"
# Echo the changed paths for the run output.
cut -c4- < /dev/null 2>/dev/null || true
git status --porcelain | cut -c4-
`;

export const refreshFixtures = defineRun({
  name: "refresh-fixtures",
  version: "1.0.0",

  inputs: Input,
  outputs: Output,

  limits: { maxDurationSec: 1800 },

  // The writeback capability — declared HERE, in the trusted run definition.
  // The container can only fill in file CONTENTS within this envelope; it can't
  // widen the branch, base, allowlist, or the workflow opt-in.
  writeback: {
    // A fixed bot branch: re-runs force-update it + the one open PR, so the
    // proposal stays current rather than accreting branches. Use `{ prefix }`
    // instead for a fresh branch (and PR) per run.
    branch: "flare-dispatch/refresh-fixtures",
    commitMessage:
      "chore: refresh fixtures\n\nGenerated by flare-dispatch refresh-fixtures.",
    pr: {
      title: "chore: refresh fixtures",
      body: "🤖 Draft opened by `flare-dispatch/refresh-fixtures`. Regenerated tracked files from the latest sources. Review before merging.",
    },
    // Only let the run touch generated fixtures — never source, never CI. With
    // no allowlist any non-traversing path is allowed; pin it for a real run.
    pathAllowlist: ["fixtures/**", "**/__fixtures__/**", "**/*.snap"],
    // `.github/workflows/**` stays gated (allowWorkflows defaults off) — this
    // run must never rewrite CI.
  },

  run: (input) =>
    Effect.gen(function* () {
      const { container, dir } = yield* step("checkout", () =>
        workspace({ repo: input.repo, sha: input.sha }),
      );

      // Run the operator's regeneration command. A non-zero exit is a normal
      // ExecResult (the command failed) — surfaced in the output; we only stage
      // a writeback when it succeeded (the Worker also gates on a successful run
      // before applying any writeback).
      const gen = yield* step("regenerate", () =>
        sandbox.exec({
          container,
          cwd: dir,
          command: input.command,
          timeoutSec: 1200,
        }),
      );

      // Stage the manifest + blobs from git's working-tree view.
      const staged = yield* step("stage-writeback", () =>
        sandbox.exec({
          container,
          cwd: dir,
          command: ["sh", "-lc", STAGE_WRITEBACK_SCRIPT],
        }),
      );
      const changedPaths = staged.stdout
        .split("\n")
        .map((s) => s.trim())
        .filter((s) => s.length > 0);

      // Upload the writeback directory artifact. The Worker reads it back and
      // (on a successful run) commits + opens the PR — see the dispatcher's
      // RunWorkflow post-run writeback step.
      const writebackUri = yield* step("upload-writeback", () =>
        artifact.upload({
          name: WRITEBACK_ARTIFACT,
          path: `${dir}/artifacts/writeback`,
          container,
        }),
      );

      return { exitCode: gen.exitCode, changedPaths, writebackUri };
    }),
});
